name: Despliegue en AWS EC2

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 📥 1. Descargar el código
              uses: actions/checkout@v4

            - name: 📂 2. Enviar archivos al servidor AWS
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  source: "."
                  target: "/home/ubuntu/portfolio"

            - name: 🚀 3. Construir y Desplegar con Docker en AWS
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      # Entramos a la carpeta donde acabamos de enviar los archivos
                      cd /home/ubuntu/portfolio

                      # Construimos la "caja" de Docker con el código nuevo
                      docker build -t mi-portafolio .

                      # Detenemos y borramos la versión anterior (si existía)
                      docker stop portafolio-app || true
                      docker rm portafolio-app || true

                      # Encendemos la nueva versión. 
                      # OJO: Conectamos el puerto 80 del servidor al 3000 del contenedor
                      docker run -d -p 80:3000 --name portafolio-app mi-portafolio
